version: "3.2"

services:

   web:
    image: demo_web
    container_name: con_demo_web
#    build:
#        context: ./web
   db:
    image: demo_db
    container_name: con_demo_db
    volumes:
      - "firstvolume:C:\\database"
#     - /C/Users/Leon/docker:/database
#     - D:\Study\docker\composetest\web\sourcevolume:C:\SQLServer
#    build:
#        context: ./db

#    environment:
#       - attach_dbs="[{'dbName':'AppVeyorTest','dbFiles':['C:\\\\SQLServer\\AppVeyorTest.mdf','C:\\\\\SQLServer\\\\AppVeyorTest_log.ldf']}]"
volumes:
  firstvolume:
#   external: true
#  sourcevolume:
networks:
  default:
    external:
      name: nat