version: "3"

services:

   webserver:
    image: composetest_web
    build:
        context: ./web
    ports:
     - "8080:80"
    volumes:
     - D:\\Study\\docker\\composetest\\web\\sourcevolume:c:\\data
   db:
    image: composetest_db
    build:
        context: ./db

    environment:
       - attach_dbs= "[{'dbName':'AppVeyorTest','dbFiles':['C:\\SQLServer\\AppVeyorTest.mdf','C:\\SQLServer\\AppVeyorTest_log.ldf']}]"
#volumes:
#  firstvolume:
#   external: true
#  sourcevolume:
networks:
  default:
    external:
      name: nat